spring:
  application:
    name: UserManagementSystem
  datasource:
    #url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    url: jdbc:mariadb://localhost:3306/usermanagement
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop